# sample-workflow-windows-latest
# docs are in the repo

name: OSSAR windows-latest
on:
  push:
    branches:
      - master

jobs:
  sample:
    name: Open Source Static Analysis Runner

    # OSSAR runs on windows-latest.
    # ubuntu-latest and macos-latest supporting coming soon
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Run OSSAR
      uses: github/ossar-action@v1
      id: ossar
    - name: Upload results to Security tab
      uses: github/codeql-action/upload-sarif@v1
      with:
        sarif_file: ${{ steps.ossar.outputs.sarifFile }}
